"""Render KTA_REGISTRIES_v0.1.xlsx to a read-only Markdown mirror.

The XLSX stays authoritative. The Markdown exists so the registry can be diffed
in git and read on a phone. Re-run after any XLSX change:

    pip install openpyxl
    python KTA/tools/render_registries.py
"""
import re
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "04_REGISTRIES" / "KTA_REGISTRIES_v0.1.xlsx"
OUT = ROOT / "04_REGISTRIES" / "KTA_REGISTRIES_v0.1_RENDERED.md"
DATE_FORMULA = re.compile(r"^=DATE\((\d+),(\d+),(\d+)\)$")


def cell_text(value):
    if value is None:
        return ""
    text = str(value)
    m = DATE_FORMULA.match(text)
    if m:
        y, mo, d = (int(g) for g in m.groups())
        return f"{y:04d}-{mo:02d}-{d:02d}"
    return text.replace("|", "\\|").replace("\n", " ")


def main():
    wb = openpyxl.load_workbook(SRC)
    lines = [
        "# KTA REGISTRIES v0.1: rendered mirror",
        "",
        f"Generated from `{SRC.name}` by `tools/render_registries.py`. **Non-authoritative mirror:** "
        "the XLSX is authoritative. Do not edit this file by hand.",
        "",
    ]
    for ws in wb.worksheets:
        rows = [r for r in ws.iter_rows(values_only=True) if any(c is not None for c in r)]
        lines += [f"## {ws.title}", ""]
        if ws.title == "Overview":
            for r in rows:
                lines.append("- " + " · ".join(cell_text(c) for c in r if c is not None))
            lines.append("")
            continue
        if not rows:
            lines += ["_(empty)_", ""]
            continue
        width = max(len([c for c in rows[0] if c is not None]), 1)
        header = [cell_text(c) for c in rows[0][:width]]
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "---|" * width)
        for r in rows[1:]:
            lines.append("| " + " | ".join(cell_text(c) for c in r[:width]) + " |")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
